/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
export {}
declare global {
  const EffectScope: (typeof import('vue'))['EffectScope']
  const FormKit: (typeof import('@formkit/vue'))['FormKit']
  const FormKitSchema: (typeof import('@formkit/vue'))['FormKitSchema']
  const LangMapAbp: (typeof import('./composables/abp-locale-i18n'))['LangMapAbp']
  const LangMapI18N: (typeof import('./composables/abp-locale-i18n'))['LangMapI18N']
  const axios: (typeof import('axios'))['default']
  const computed: (typeof import('vue'))['computed']
  const createApp: (typeof import('vue'))['createApp']
  const customRef: (typeof import('vue'))['customRef']
  const defineAsyncComponent: (typeof import('vue'))['defineAsyncComponent']
  const defineComponent: (typeof import('vue'))['defineComponent']
  const defineLoader: (typeof import('vue-router/auto'))['defineLoader']
  const definePage: (typeof import('unplugin-vue-router/runtime'))['_definePage']
  const effectScope: (typeof import('vue'))['effectScope']
  const getCurrentInstance: (typeof import('vue'))['getCurrentInstance']
  const getCurrentScope: (typeof import('vue'))['getCurrentScope']
  const h: (typeof import('vue'))['h']
  const inject: (typeof import('vue'))['inject']
  const isDark: (typeof import('./composables/dark'))['isDark']
  const isGranted: (typeof import('./composables/acl'))['isGranted']
  const isGrantedAnyOf: (typeof import('./composables/acl'))['isGrantedAnyOf']
  const isProxy: (typeof import('vue'))['isProxy']
  const isReactive: (typeof import('vue'))['isReactive']
  const isReadonly: (typeof import('vue'))['isReadonly']
  const isRef: (typeof import('vue'))['isRef']
  const markRaw: (typeof import('vue'))['markRaw']
  const menuAclResolve: (typeof import('./composables/acl'))['menuAclResolve']
  const nextTick: (typeof import('vue'))['nextTick']
  const onActivated: (typeof import('vue'))['onActivated']
  const onBeforeMount: (typeof import('vue'))['onBeforeMount']
  const onBeforeRouteLeave: (typeof import('vue-router/auto'))['onBeforeRouteLeave']
  const onBeforeRouteUpdate: (typeof import('vue-router/auto'))['onBeforeRouteUpdate']
  const onBeforeUnmount: (typeof import('vue'))['onBeforeUnmount']
  const onBeforeUpdate: (typeof import('vue'))['onBeforeUpdate']
  const onDeactivated: (typeof import('vue'))['onDeactivated']
  const onErrorCaptured: (typeof import('vue'))['onErrorCaptured']
  const onMounted: (typeof import('vue'))['onMounted']
  const onRenderTracked: (typeof import('vue'))['onRenderTracked']
  const onRenderTriggered: (typeof import('vue'))['onRenderTriggered']
  const onScopeDispose: (typeof import('vue'))['onScopeDispose']
  const onServerPrefetch: (typeof import('vue'))['onServerPrefetch']
  const onUnmounted: (typeof import('vue'))['onUnmounted']
  const onUpdated: (typeof import('vue'))['onUpdated']
  const provide: (typeof import('vue'))['provide']
  const reactive: (typeof import('vue'))['reactive']
  const readonly: (typeof import('vue'))['readonly']
  const ref: (typeof import('vue'))['ref']
  const resolveComponent: (typeof import('vue'))['resolveComponent']
  const shallowReactive: (typeof import('vue'))['shallowReactive']
  const shallowReadonly: (typeof import('vue'))['shallowReadonly']
  const shallowRef: (typeof import('vue'))['shallowRef']
  const storeToRefs: (typeof import('pinia'))['storeToRefs']
  const toRaw: (typeof import('vue'))['toRaw']
  const toRef: (typeof import('vue'))['toRef']
  const toRefs: (typeof import('vue'))['toRefs']
  const toValue: (typeof import('vue'))['toValue']
  const toggleDark: (typeof import('./composables/dark'))['toggleDark']
  const triggerRef: (typeof import('vue'))['triggerRef']
  const unref: (typeof import('vue'))['unref']
  const useAbpLocalizationAdapter: (typeof import('./composables/abp-locale-i18n'))['useAbpLocalizationAdapter']
  const useAppStore: (typeof import('./stores/app'))['useAppStore']
  const useAttrs: (typeof import('vue'))['useAttrs']
  const useAuth: (typeof import('vue3-oidc'))['useAuth']
  const useAuthStore: (typeof import('./stores/auth'))['useAuthStore']
  const useCssModule: (typeof import('vue'))['useCssModule']
  const useCssVars: (typeof import('vue'))['useCssVars']
  const useEventBus: (typeof import('./composables/eventBus'))['useEventBus']
  const useFeatureStore: (typeof import('./stores/feature'))['useFeatureStore']
  const useGlobalFeatureStore: (typeof import('./stores/globalFeature'))['useGlobalFeatureStore']
  const useI18n: (typeof import('vue-i18n'))['useI18n']
  const useLanguageStore: (typeof import('./stores/language'))['useLanguageStore']
  const useLink: (typeof import('vue-router/auto'))['useLink']
  const useLocalizationStore: (typeof import('./stores/localization'))['useLocalizationStore']
  const useOidcStore: (typeof import('vue3-oidc'))['useOidcStore']
  const useRoute: (typeof import('vue-router/auto'))['useRoute']
  const useRouter: (typeof import('vue-router/auto'))['useRouter']
  const useSettingStore: (typeof import('./stores/setting'))['useSettingStore']
  const useSlots: (typeof import('vue'))['useSlots']
  const useTokenService: (typeof import('./composables/token'))['useTokenService']
  const watch: (typeof import('vue'))['watch']
  const watchEffect: (typeof import('vue'))['watchEffect']
  const watchPostEffect: (typeof import('vue'))['watchPostEffect']
  const watchSyncEffect: (typeof import('vue'))['watchSyncEffect']
}
// for type re-export
declare global {
  // @ts-ignore
  export type {
    Component,
    ComponentPublicInstance,
    ComputedRef,
    ExtractDefaultPropTypes,
    ExtractPropTypes,
    ExtractPublicPropTypes,
    InjectionKey,
    PropType,
    Ref,
    VNode,
    WritableComputedRef
  } from 'vue'
}
