/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BaseHeader: (typeof import('./components/layouts/BaseHeader.vue'))['default']
    Breadcrumb: (typeof import('./components/layouts/Breadcrumb.vue'))['default']
    ChangePwd: (typeof import('./components/layouts/top/ChangePwd.vue'))['default']
    Collapse: (typeof import('./components/layouts/top/Collapse.vue'))['default']
    EditProfile: (typeof import('./components/layouts/top/EditProfile.vue'))['default']
    ElButton: (typeof import('element-plus/es'))['ElButton']
    ElCard: (typeof import('element-plus/es'))['ElCard']
    ElCol: (typeof import('element-plus/es'))['ElCol']
    ElConfigProvider: (typeof import('element-plus/es'))['ElConfigProvider']
    ElDialog: (typeof import('element-plus/es'))['ElDialog']
    ElDropdown: (typeof import('element-plus/es'))['ElDropdown']
    ElDropdownItem: (typeof import('element-plus/es'))['ElDropdownItem']
    ElDropdownMenu: (typeof import('element-plus/es'))['ElDropdownMenu']
    ElForm: (typeof import('element-plus/es'))['ElForm']
    ElFormItem: (typeof import('element-plus/es'))['ElFormItem']
    ElIcon: (typeof import('element-plus/es'))['ElIcon']
    ElInput: (typeof import('element-plus/es'))['ElInput']
    ElMenu: (typeof import('element-plus/es'))['ElMenu']
    ElMenuItem: (typeof import('element-plus/es'))['ElMenuItem']
    ElPagination: (typeof import('element-plus/es'))['ElPagination']
    ElPopconfirm: (typeof import('element-plus/es'))['ElPopconfirm']
    ElRow: (typeof import('element-plus/es'))['ElRow']
    ElScrollbar: (typeof import('element-plus/es'))['ElScrollbar']
    ElSkeleton: (typeof import('element-plus/es'))['ElSkeleton']
    ElSubMenu: (typeof import('element-plus/es'))['ElSubMenu']
    ElTable: (typeof import('element-plus/es'))['ElTable']
    ElTableColumn: (typeof import('element-plus/es'))['ElTableColumn']
    ElTag: (typeof import('element-plus/es'))['ElTag']
    LanguageSwitch: (typeof import('./components/layouts/top/LanguageSwitch.vue'))['default']
    ListPage: (typeof import('./components/pages/ListPage.vue'))['default']
    Logo: (typeof import('./components/layouts/left/Logo.vue'))['default']
    Menu: (typeof import('./components/layouts/left/Menu.vue'))['default']
    MenuItem: (typeof import('./components/layouts/left/MenuItem.vue'))['default']
    RoleLookup: (typeof import('./components/lookup/RoleLookup.vue'))['default']
    RouterLink: (typeof import('vue-router'))['RouterLink']
    RouterView: (typeof import('vue-router'))['RouterView']
    ToolHeader: (typeof import('./components/layouts/top/ToolHeader.vue'))['default']
    UserInfo: (typeof import('./components/layouts/top/UserInfo.vue'))['default']
    UserLookup: (typeof import('./components/lookup/UserLookup.vue'))['default']
  }
  export interface ComponentCustomProperties {
    vLoading: (typeof import('element-plus/es'))['ElLoadingDirective']
  }
}
